### ISSUE TITLE
Regenerate Slides

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1324]
**Emmanuel**
- [x] exploring-linear-relationships
- [x] exploring-logarithmic-relationships
- [x] exploring-quadratic-relationships
- [x] choosing-your-dataset (the slides.md file has been updated, but it still links to an outdated tutorial and template for adding your own data #1334)
- [x] defining-table-functions #1346
- [x] ds-intro
- [x] scatter-plots
- [x] simple-data-types
- [x] lookups
- [x] advanced-displays
- [x] debugging
- [x] bar-and-pie-charts
- [x] data-cycle
- [x] contracts-tables-displays - need to add new coe pages
- [x] grouped-samples
- [x] standard-deviation
- [x] problem-decomposition (pending #1363 )
- [x] probability-inference (need to integrate Nancy Pfenning's feedback first)

**Rachel**
- [x] absolute-value-and-opposites
- [x] absolute-value-and-opposites-2
- [x] associative-property
- [x] codap-bar-charts
- [x] codap-exploring
- [x] codap-transformers-1
- [x] codap-transformers-2
- [x] computation
- [x] distributive-property
- [x] equivalence
- [x] evaluating-exponents
- [x] exponent-expressions-with-negatives
- [x] identity-property
- [x] translating
- [x] commutative-property
- [x] combinatorics-combination
- [x] combinatorics-permutation
- [x] composing-table-operations 
- [x] checking-your-work
- [x] correlations
- [x] data-collection
- [x] ethics-privacy-and-bias
- [x] table-functions ("Review" section needs to be updated before slides can be finalized, @schanzer)
- [x] threats-to-validity (Waiting on decision re: #1365)

**Flannery**

- [x] computing-needs-all-voices 
- [x] contracts
- [x] coordinates
- [x] distance-formula
- [x] flags
- [x] inequalities3-sam
- [x] linear-regression
- [x] piecewise-functions-conditionals
- [x] player-animation
- [x] defining-values
- [x] function-composition
- [x] function-definition-linear
- [x] function-notation
- [x] functions-dr
- [x] functions-for-character-animation
- [x] functions-make-life-easier
- [x] functions-can-be-linear
- [x] functions-examples-definitions
- [x] functions-vertical-line-test
- [x] inequalities-collision **(Note: The link to `Word Problem: is-collision` never build correctly and got fixed by hand in both decks. Made issue #1363 about this. Also #1364 needs to be addressed collide? or collision?)**
- [x] box-plots (decide re: kinesthetic)
- [x] histograms (decide re: kinesthetic)
- [x] histograms2 (update with #1353)
- [x] measures-of-center
- [x] surface-area-rect-prism
- [x] making-game-images
- [x] inequalities1-simple
- [x] inequalities2-compound
- [x] numbers-inside-video-games
- [x] order-of-operations
- [x] Audit slides for projects

**Comment by schanzer** [comment]
@retabak no, the details are exactly where you need to be. Only check off lessons for which you are certain there are no changes.

**Comment by schanzer** [comment]
@flannery-denny I didn't want to close until we'd addressed your opt-project concerns, but I'm ok closing if you are
