### ISSUE TITLE
Desmos Cleanup

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1544]
The following lessons include required Desmos activities:

- [x] Coordinates
- [x] Exploring Exponential Models
- [x] Exploring logarithmic Models
- [x] Exploring quadratic Models
- [x] Hour of Data

The following lessons include `@opt-online-exercise{desmos}` links
- [x] Order of Operations
- [x] Flags
- [x] function definition linear
- [x] function-notation
- [x] Functions can be linear
- [x] inequalities2
- [x] contracts
- [x] function composition
- [x] defining values
- [x] functions-examples-definitions
- [x]  box-plots
- [x] correlations

### TODO

- Consolidate into 1 activity per-lesson
- Add that activity as @opt-online-exercise if it's optional, @starter-file if it's not

**Comment by flannery-denny** [comment]
@retabak Realizing that this plan is very clear for lessons where Desmos activities are required, but 

**What makes most sense for lessons with require and optional Desmos activities?**
- Make one file that has all of the required Desmos activities and leave the optional activities as individual items, since that makes it easiest to reference them?
- Make one file that has all of the required Desmos activities and a separate file that has all of the optional activities - then reference the optional activities with their slide title but linking to the general optional deck?
- Make one file that has all of the Desmos activities in the order that they are referenced in the lesson plan (which means teachers might have to skip their students passed some slides in order to do the required parts)
- Make one file that has all of the required activities at the beginning and all of the optional activities after that?

**What makes most sense for lesson with only optional Desmos activities?**
- A single file that has all of the optional activities - then reference the optional activities with their slide title but link to the general optional deck?
-  leave the optional activities as individual items, since that makes it easiest to reference them?

**Comment by flannery-denny** [comment]
@retabak Is there an easy way to convert a desmos calculator file to an activity? Or will I have to have the calculator activity open as a model and recreate it in an activity?

Take this for example. I know how to duplicate it, but I'm not seeing something I can click on that will switch it over. 
https://www.desmos.com/calculator/yoovliwhhd

**Comment by retabak** [comment]
Yes, there is an easy way. 

Copy the url of the calculator activity. Paste it into the first row (which is blue in this screenshot). Everything will magically appear.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/84afe8f5-5393-4606-9a8b-a79514021436)

**Comment by flannery-denny** [comment]
@retabak I'm still not efficient with combining Desmos activities. I'm making a list of things I'd like help with here and will set up a time to zoom via slack

- Combine these two activities
--  [https://teacher.desmos.com/activitybuilder/custom/5fc53aeef328540d3ad2123c](https://teacher.desmos.com/activitybuilder/custom/5fc53aeef328540d3ad2123c)
-- [https://teacher.desmos.com/activitybuilder/custom/5fc90f1289c78e0d2a5bccfc](https://teacher.desmos.com/activitybuilder/custom/5fc90f1289c78e0d2a5bccfc)
- Combine these two activities
-- [https://teacher.desmos.com/activitybuilder/custom/5fc9328d18307e2e492ca0d8](https://teacher.desmos.com/activitybuilder/custom/5fc9328d18307e2e492ca0d8)
-- [https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68](https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68l)

**Comment by retabak** [comment]
I'm happy to zoom anytime.

If it would be easier for me to complete this task, I'm happy to do it. Just let me know. I don't want to deny you the opportunity to become a more proficient desmos user if that is of interest.
