### ISSUE TITLE
Convert fall2024 lessons to new slide infrastructure

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1669]
FD
- [x] advanced-displays
- [x] bar-and-pie-charts 
- [x] checking-your-work #1924
- [x] combinatorics-combination 
- [x] combinatorics-permutation 
- [x] computing-needs-all-voices 
- [x] contracts #1890
- [x] contracts-tables-displays #1913 #1976 
- [x] coordinates
- [x] correlations 
- [x] data-cycle #1993 #1782, #1765, 
- [x] debugging 
- [x] defining-table-functions - #1991
- [x] defining-values - waiting to hear how CPO is replacing identifier! 
- [x] distance-formula #1898 #1899 #1897 #1895
- [x] inequalities-collision 
- [x] inequalities1-simple  #1973
- [x] inequalities2-compound (#1900) #1901 #1973
- [x] inequalities3-sam #1902 #1900
- [x] lookups #1904 #1922
- [x] making-game-images #1900 #1905
- [x] measures-of-center
- [x] numbers-inside-video-games
- [x] order-of-operations #1917 #1939 #1975 
- [x] piecewise-functions-conditionals #1907
- [x] player-animation #1904 #1923
- [x] function-composition
- [x] function-definition-linear #1910
- [x] function-notation #1923
- [x] functions-can-be-linear #1925 #1959 #1964
- [x] functions-dr #1914
- [x] functions-examples-definitions
- [x] functions-for-character-animation
- [x] functions-make-life-easier #1926
- [x] functions-vertical-line-test #1933
- [x] problem-decomposition #1928
- [x] scatter-plots #1929 perhaps replace first image so that that it includes a point cloud?
- [x] simple-data-types _runaway directive_
- [x] standard-deviation
- [x] surface-area-rect-prism
- [x] threats-to-validity _resolve wording of threat to validity from describing LR_
- [x] transform-compose-images

Projects -- **RT and ES discussed and agreed that these do not require slides; can use dummy slide ID**
-  project-beautiful-data
-  project-data-exploration
-  project-design-a-survey
-  project-function
-  project-infographic
-  project-logo
-  project-research-paper
-  project-threats
-  project-video-game

RT
- [x] histograms
- [x] histograms-codap
- [x] grouped-samples
- [x] grouped-samples-codap
- [x] linear-regression #1861 
- [x] linear-regression-codap #1861 
- [x] ethics-privacy-and-bias
- [x] ethics-privacy-bias-codap
- [x] box-plots  #1763, #1675
- [x] box-plots-codap
- [x] absolute-value-and-opposites
- [x] absolute-value-and-opposites-wescheme
- [x] additive-inverse
- [x] additive inverse-wescheme
- [x] multiplicative-inverse
- [x] multiplicative-inverse-wescheme
- [x] associative-property
- [x] associative-property-wescheme
- [x] codap-building-codap
- [x] codap-composing-codap
- [x] codap-dot-plots-bar-charts-codap
- [x] codap-exploring-codap
- [x] codap-filtering-codap
- [x] commutative-property
- [x] commutative-property-wescheme
- [x] composing-table-operations
- [x] data-cycle-codap - pending #1765
- [x] data-collection
- [x] data-collection-codap
- [x] distributive-property #1919 
- [x] distributive-property-wescheme
- [x] dot-plots-bar-charts-codap #1972
- [x] equivalence
- [x] equivalence-wescheme
- [x] evaluating-exponents - #1917
- [x] evaluating-exponents-wescheme
- [x] exponent-expressions-with-negatives
- [x] translating
- [x] translating-wescheme

ES

- [x] identity-property - #1915, #1916
- [x] identity-property-wescheme
- [x] variables 
- [x] variables-wescheme
- [x] probability-inference-codap
- [x] probability-inference
- [x] exponent-expressions-with-negatives-wescheme
- [x] absolute-value-and-opposites-2
- [x] absolute-value-and-opposites-2-wescheme
- [x] exploring-logarithmic-models
- [x] exploring-exponential-models
- [x] exploring-quadratic-models
- [x] exploring-linear-models
- [x] ds-intro
- [x] ds-intro-codap
- [x] choosing-your-dataset #1767
- [x] visualizing-the-shape-of-data
- [x] choosing-your-dataset-codap
- [x]  re-adding-collisions
- [x] re-adding-levels
- [x] re-build-your-own-animation
- [x] re-functions-that-ask-questions
- [x] re-intro-to-data-structures
- [x] re-key-events
- [x] re-making-pong
- [x] re-nested-structures
- [x] re-refactoring
- [x] re-scoring
- [x] re-structures-reactors-animations
- [x] re-timers
- [x] re-your-own-drawing-functions

No Slides To be Built
- hoc-data
- hoc-wescheme-intro
- hoc-winter
- hoc-winter-parley

**Comment by ds26gte** [comment]
After experimenting with how to programmatically convert tables from index.adoc to zlides.md, arrived at the following impressions and solution attempt:

We're often using `|===` tables in almost the full diversity that AsciiDoc allows. In particular, we're using multiline cells, sometimes with multiple paragraphs, sometimes with (bulleted) lists. Markdown tables seem to require each row to correspond to one input line.

Given this, for simple tables, it may be best to continue to write  slide-intended tables as before even in the AsciiDoc source. The `@table` line can be safely ignored by AsciiDoc, and this type of (simple) table will work for both AsciiDoc and slides, so they don't need to be written two different ways. 

However, for the general table, we still want the more featureful AsciiDoc syntax, while being satisfied with a simpler copy for slides. This is not too bad anyway, since the slides table doesn't have enough space to render in great complexity anyway. To accommodate this, I've added directives `@ifslide` and `@ifnotslide` which can be used to wrap tables meant for slides only and those meant for AsciiDoc only respectively. I've also made `@table` be a no-op in AsciiDoc. (Of course we can use `@ifslide` and `@ifnotslide` for other purposes too, not just for annotating tables.)

This should let us write the simple tables once and, in situations where this isn't enough, we are still able to write a more complicated table for AsciiDoc and a less complicated one for slides. What say?

**Comment by flannery-denny** [comment]
Decide how to handle roleplay

Is it written in lesson instruction voice or teacher facing?
<img width="679" alt="Screen Shot 2023-12-11 at 2 10 58 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/37c863e9-22ca-4cba-bee8-d3b021fd815b">

Should we switch between roleplay and QandA? 
<img width="674" alt="Screen Shot 2023-12-11 at 1 55 40 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/255746db-1347-47d9-b462-f79839c02f29">
<img width="684" alt="Screen Shot 2023-12-11 at 2 09 45 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0355b6c8-a6f4-45c3-8d0e-12a55d2f6b4b">

Use QandA?
<img width="676" alt="Screen Shot 2023-12-11 at 2 06 15 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a64c6539-1756-48f5-8509-568ee97fcd1c">

Or add the possibility for role play to have QandA directives. Perhaps this would be accomplished by using `@roleplayQandA` instead of `@QandA`

**Comment by schanzer** [comment]
@flannery-denny documenting our agreement last Tuesday that role-play should be written in student-facing voice, with role-play used to describe the scene and smaller instructions ("let's have TARGET and DANGER switch places!") written as instruction within QandA (probably using some custom formatting)

**Comment by flannery-denny** [comment]
@retabak We can close this issue as soon as you check off the `dot-plots-bar-charts-codap` :) Woohoo!
