### ISSUE TITLE
Box Plot Rethink

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2129]
Since neither of the box plot issues @retabak has created are urgent, it makes most sense to me to tackle them together by restructuring the lesson. Work for this issue will happen on a separate `boxplot` branch. I will likely add some more bullets here as I think through what needs to happen.

- [x] #2104 
- [x] #2111 - This will be an opt-printable for 2024, but I think that the changes can all go live this year.
- [x] Consider whether it makes sense to tackle #2085 at the same time.
- [x] Don't forget to update the slide deck! (waiting on #2145)

**Comment by flannery-denny** [comment]
@schanzer This lesson currently talks about deviation and spread. Wondering if we should start using the word variation here. Make sense to you? If so, does this distinction between the 3 terms sit well for you. I don't intend to put these words anywhere in particular, but I want to make sure I'm writing from a place of common understanding.

- Variation: Refers to the degree to which data points differ from their mean value. It’s a broad term encompassing various measures of dispersion. _Used to describe a dataset_
- Deviation: Specifically, it’s the distance between a data point and the mean value. A larger deviation indicates a greater difference from the mean. _Used to describe individual points_
- Spread: Describes the range or extent to which data points are dispersed from the mean. A larger spread means data points are more scattered, while a smaller spread indicates they are closer to the mean. _Used to describe a dataset_

**Comment by retabak** [comment]
I am totally not working today (lol) but happened to notice this and wanted to jump in to say that the common core standards and the research I encountered use the term "variability," e.g:

[CCSS.MATH.CONTENT.6.SP.B.5.D](https://www.thecorestandards.org/Math/Content/6/SP/B/5/d/)
Summarize numerical data sets in relation to their context, such as by:
Relating the choice of measures of center and variability to the shape of the data distribution and the context in which the data were gathered.

**Comment by schanzer** [comment]
+1 to building up the use of "variability"!

**Comment by flannery-denny** [comment]
Thanks @retabak! Do you happen to know whether box plots are a 6th grade topic? If you don't know I can look. And if they're not, we need to make sure we also add this discussion to something that would be seen by sixth graders.

**Comment by retabak** [comment]
100% introduced in sixth grade.
