### ISSUE TITLE
Split Alg 2 lessons into discreet units & generate a todo list of materials that need to be fleshed out

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2158]
- [x] #2207
- [x] quadratic
- [x] exponential
- [x] logarithmic
- [x] periodic
- [x] make sure that simpsons paradox is given its own lesson
- [x] audit images and remove duplicates
- [x] make todo list (https://github.com/bootstrapworld/curriculum/issues/2214)
