### ISSUE TITLE
Last wescheme algebra workbook list for August 2020

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#350]
- [x] typo on attributes page I fixed didn't get pushed before this build. confirm it survives the merge in final printing.
- [x] p7 - order of operations notes. third bullet. Is there a way to get the ( / ) all on one line. Maybe with the word division. fourth bullet - write in math so that there is no parentheses around 10 x 7.
- [x] p16 - translating coe to cod w sqrt - add the word "hint" before the function name? Change first column header from Arithmetic to Expression.
- [x] p17 Exporing image functions - not sure there's enough room to draw circles in those table rows. Can we make them bigger? Also there is no number 1 on this page but the mystery functions are 2,3,4.
- [x] p.19#4 says wescheme. That's fine if the file isn't also used in pyret.
- [x] p.20 in #2 and #3 the word scale is used and should be `scale`
- [x] p.22 capitalize Code in directions (the inconsistency of capitalized and lower case use of the word code led me to make an ex. decision that they would all be capitalized this year. In the Sam Intro it's italicized, which may be better. Big picture I think we need to make some decisions about what should be bolded / italicized / capitalized. For example, the word Example is also EXAMPLE is also example and sometimes bolded.)
- [x] p 25 confirm that this is where gt happens in the lesson plans. Add directions to complete the second for bc.
- [x] p 26 fast functions - should there be directions here?
- [x] p.29 Do we still want this here? - YES (ES)
- [x] p.32 wording of rideshare could probably be clearer. maybe globogym wording should be joining fee instead of initiation fee.
- [x] p.40 revenue and cost are both about glasses and profit is about Sally.
- [x] p.41 Inequalities Launch - still curious whether this is the very first time students see the word Boolean and whether it might need an acknowledgement on this page or in the previous notes section. _ES:_ Students will have seen that word before, according to the lesson plan. They'll also have seen it explained in the immediately-preceding notes page.
- [x] p.44 #4 could we and ampersand between and & or?
- [x] p.46 nice work getting 1 and 2 on separate lines - I'll have to look & see how you did it. Now that they're on separate lines, the and at the end of the first one should probably go.
- [x] p.50 update player. In the pyret version the keys are "up" and "down". In Wescheme they're 'up', 'down' and 'w'. Can we not have quotes here? Do we want w or to stick to up and down?
- [x] p.53 Thought more about this Distance scaffold. It would be great to add a sentence explaining how x1 y1 connect to (0,2) and x2 y2 connect to (4,5). Can we give the real distance formula here?  for lack of better symbols & brainpower... sqrt((x2-x1)^2 + (y2-y1)^2) in math. If we're using linelength (which is probably also fine) seems the commas don't help and the parentheses should include line length so it more closely resembles math.
- [x] contract example didn't get pushed before this build. The pdf on my computer shows words from the directions cut off because text wrapping because goes beyond the edge of the table. confirm that all words are visible on all 8 contract pages before sending to print.

---
- [ ] Design recipe pages. Could there be @vspace{2ex} or more between the dividing line and the start of the lower problem?
- [ ] p.48 #9 should String be `String` - _ES: this is not code_

**Comment by schanzer** [comment]
@flannery-denny I like the suggestion of consistently capitalizing Code when it's used as a representation, just as we do with Circle of Evaluation. However, example _should_ be capitalized and bolded...sometimes. When we refer to code in WeScheme, we're talking about the `EXAMPLE` keyword. When we refer to code in Pyret, we're talking about the *examples:* keyword. And in prose, we ask students to write "examples".

**Comment by schanzer** [comment]
I don't think we can add space after the dividing line on the DR pages. Some of them are taller than others, and vertical space is at an extreme premium.

**Comment by flannery-denny** [comment]
@schanzer Booleans are not mentioned in the notes I see in the workbook. Is there a page you've written that you didn't add to the workbook?
