### ISSUE TITLE
DS Workbook fixes - pdf page numbers used

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#504]
Data Science workbook looks great!
- [x] page 24 - Data Displays & Lookups - Bullet 1 _students'_ should not have an apostrophe
- [x] Page 30 - There should be a clickable lInk to the "Table Methods Starter File" from this page
- [x] Page 38 - add a colon to "A good purpose statement should always explain".
- [x] Page 38 - Not sure what lesson this is, but it would be good to confirm that all of the sentences that are written made it onto the page. It's possible that the "definition" section only has one line of text, but it seems likely that we should be seeing an example of the function definition that is getting cut off.
- [x] Page 48 - Doesn't have any room for student to actually Notice and Wonder. Did you want the Sample response showing in the student workbook?
- [x] Page 49 - Word-Problem: species-color. Printed area of the page is strangely narrow.
- [x] Page 51 - Sampling and Inference - #2 should not be a question. Not totally sure what the best solution is, but I think probably the question should be deleted altogether and #2 should start with the line that follows, "Type each..." 
- [x] Page 51 - the @fitb on this page are the wrong size. Either shorten them so they fit with the questions or use @span{.blankline} instead.
- [x] Page 52 - I would suggest making the rows of this table taller to give students more space to write.
- [x] Page 55 - Could use more specific directions
- [x] Page 63 - The similarities / Differences table at the bottom of the page has crazy short rows and would be impossible to write in.
- [x] Page 73 - #1 could use more space
- [x] Page 73 - Missing the numberline to do #4.
- [x] Do you want page 78 and page 79 to look this similar?
- [x] Page 86 - would look better if final @fitb lengths were adjusted
- [x] page 89 - if this were landscape, student might have more space t write.

Will pick up here later.

- [x] Page 2 - ok to put Ed's name at the bottom of the list? ;)

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] page 30 still needs a clickable link to the starter file. Looks like it got added to page 31.
- [ ] page 51 - Sampling and inference is now skips from 1 to 3.. deploy @n 
- [ ] page 90 @fitb lengths are inconsisent. Number 2 looks better than 1 or 3.
- [ ] page 93 grammar for number 1 is funky. Maybe simplify to "read the case study you were assigned"
- [ ] page 94. I don't think the last one is a good example. 
- [ ] page 100. There are three empty design recipes at the back. Can we turn off directions for them? It's not really a step that we would have students fill in on their own.

**Comment by schanzer** [comment]
Turning off directions is both slightly hacky, _and_ undermines teachers who want to use those worksheets for specific word problems. In those situations, we _want_ to give students a place to write the directions.

**Comment by flannery-denny** [comment]
@schanzer I'm ok with you deciding not to make the suggested change, but I highly doubt that students will be able to write directions in in the alotted space.

**Comment by flannery-denny** [comment]
Page 97 - fake news. built w content missing

If you have energy, page 68 directions above notice & wonder don't seem to jive with the pedagogy (they are specific leading questions and it's unclear whether they need to be responded to.)

**Comment by schanzer** [comment]
@flannery-denny if the latest copy looks good, feel free to close!
